# files/settings.yml
parser:
  args:
    device: mps
    vlm_candidate: QwenV25Infer
    embedding_candidate: ColPaliInfer
    models:
      - QwenV25Infer
      - ColPaliInfer

model_manager:
  general:
    huggingface_api_token: ""
    model_loading: "local"
  models:
    QwenV25Infer:
      model_name_or_url: "Qwen/Qwen2.5-VL-3B-Instruct"
      device: mps
      api_endpoint": ""
    ColPaliInfer:
      model_name_or_url: "vidore/colqwen2-v1.0"
      device: mps
      api_endpoint": ""