# config/prompts.yml

# ------------------------------------------
# 1) Common system prompt (insert schema via {schema})
# ------------------------------------------
system: |
  You are a document-extraction agent. You must produce exactly one JSON object that
  fully conforms to the following JSON schema (no extra keys, no extra output):

  {schema}

# ------------------------------------------
# 2) Common user‐prompt postfix
# ------------------------------------------
postfix: |
  Output only the JSON object; do NOT output any extra text or explanation.

# ------------------------------------------
# 3) Base templates for each extraction type (no page references)
# ------------------------------------------
user:
  key_value: |
      Now: extract the field "{field_name}" (description: {description}).
      Previous value: "{prev_value}"
      {instruction}
      {postfix}

  bullet_points: |
      Now: extract all bullet points for "{field_name}" (description: {description}).
      {instruction}
      {postfix}

fallback: |
  Extract the field "{field_name}" (description: {description}) as {extraction_type}.
  Previous value: "{prev_value}"
  {postfix}

# ------------------------------------------
# 4) Instruction fragments (keys must match ExtractionItem attributes)
# ------------------------------------------
instructions:
  # Used when item.multipage_value == true
  multipage_value: |
    • This field may span multiple pages; set "continue_next_page": true if more pages remain; otherwise false.
    • If the field is not present at this step, set "value": "" and "continue_next_page": false.

  # Used when item.multiline_value == true
  multiline_value: |
    • This field may contain multiple lines. Treat line breaks as part of "value".
    • Always set "continue_next_page": false (single-page).
    • If not found, set "value": "" and "continue_next_page": false.

  # Used when neither multipage_value nor multiline_value is true
  single: |
    • This field is single-page and single-line; always set "continue_next_page": false.
    • If not found, set "value": "" and "continue_next_page": false.