model_loading: "local"  # Options: "local" or "api"
huggingface_api_token: ""
QwenV25Infer_model_name_or_url: "Qwen/Qwen2.5-VL-3B-Instruct"  # For local loading
ColPaliInfer_model_name_or_url: "vidore/colqwen2-v1.0"  # Replace with the actual model name or URL
api_endpoint: ""  # For API loading
