model_loading: "local"  # Options: "local" or "api"
huggingface_api_token: ""
qwen_model_name_or_url: "Qwen/Qwen2.5-VL-3B-Instruct"  # For local loading
colpali_model_name_or_url: "vidore/colqwen2-v1.0"  # Replace with the actual model name or URL
api_endpoint: ""  # For API loading

pdf_path: "/Users/saketm10/Projects/extraction_by_config/dataset/1008.pdf"
output_json_path: "output/1008.json"
extraction_config_path: "de_config/1008.json"
